  version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    assignees: []
    reviewers: []
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "main"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    open-pull-requests-limit: 10