; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Upload settings
upload_port = COM3

; Serial Monitor options
monitor_port = COM3
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=3

; Library dependencies
lib_deps =
    bblanchon/ArduinoJson@^6.21.0 